# Generated by Django 5.1.2 on 2024-10-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chamada', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('rm', models.CharField(max_length=20, unique=True)),
                ('ra_rg', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('transferido', 'Transferido'), ('suplente', 'Suplente')], max_length=20)),
            ],
        ),
    ]
