# Generated by Django 5.1.2 on 2024-10-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_aulas_previstas', models.IntegerField()),
                ('quantidade_aulas_dadas', models.IntegerField()),
            ],
        ),
    ]
