# Generated by Django 5.1.2 on 2024-10-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='quantidade_aulas_dadas',
            new_name='aulas_dadas_bimestre1',
        ),
        migrations.AddField(
            model_name='professor',
            name='aulas_dadas_bimestre2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='aulas_dadas_bimestre3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='aulas_dadas_bimestre4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
