# Generated by Django 5.1.2 on 2024-10-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='quantidade_aulas_previstas',
        ),
        migrations.AddField(
            model_name='professor',
            name='aulas_previstas_bimestre1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='aulas_previstas_bimestre2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='aulas_previstas_bimestre3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='aulas_previstas_bimestre4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='aulas_dadas_bimestre1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='aulas_dadas_bimestre2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='aulas_dadas_bimestre3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='aulas_dadas_bimestre4',
            field=models.IntegerField(default=0),
        ),
    ]
