# Generated by Django 5.1.2 on 2024-10-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_professor_quantidade_aulas_previstas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('alunos', models.ManyToManyField(to='core.aluno')),
                ('professores', models.ManyToManyField(to='core.professor')),
            ],
        ),
    ]
