# Generated by Django 5.1.2 on 2024-10-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_bimestre1', models.FloatField(default=0)),
                ('nota_bimestre2', models.FloatField(default=0)),
                ('nota_bimestre3', models.FloatField(default=0)),
                ('nota_bimestre4', models.FloatField(default=0)),
                ('media_final', models.FloatField(default=0)),
                ('faltas', models.IntegerField(default=0)),
                ('status_final', models.CharField(choices=[('P', 'Promovido'), ('PC', 'Promovido pelo conselho'), ('T', 'Transferido'), ('R', 'Retido'), ('NC', 'Não Comparecimento'), ('AB', 'Abandono'), ('RC', 'Reclassificado'), ('RM', 'Remanejado')], default='P', max_length=2)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
            ],
        ),
    ]
