# Generated by Django 5.1.2 on 2024-11-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_faltas_nota_faltas_bimestre1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='numero_chamada',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ra_rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('transferido', 'Transferido'), ('suplente', 'Suplente')], default='ativo', max_length=11),
        ),
    ]
