# Generated by Django 5.1.2 on 2024-11-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_professor_email_professor_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplinas',
            field=models.ManyToManyField(related_name='professores', to='core.disciplina'),
        ),
    ]
